(add-to-list 'load-path "~/.guix-profile/share/emacs/site-lisp")
(guix-emacs-autoload-packages)
(require 'evil)
(evil-mode 1)
;(fset 'evil-visual-update-x-selection 'ignore)
(require 'ido)
(ido-mode 1)
(require 'rainbow-blocks)
(add-hook 'prog-mode-hook 'rainbow-blocks-mode)
(add-hook 'after-init-hook 'global-company-mode)
(require 'tramp)
(setq tramp-default-method "ssh")
(require 'matrix-client)
